# Generated by Django 2.2.12 on 2020-05-07 05:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
