# Generated by Django 2.2.12 on 2020-05-07 07:06

from django.db import migrations
import django.utils.timezone
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20200507_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='tz',
            field=timezone_field.fields.TimeZoneField(default=django.utils.timezone.now),
        ),
    ]
