# Generated by Django 2.2.12 on 2020-05-07 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20200507_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='tz',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
