# Generated by Django 2.2.12 on 2020-05-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_auto_20200507_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='main_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ok', models.BooleanField()),
            ],
        ),
    ]
