# Generated by Django 2.2.12 on 2020-05-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_main_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='main_class',
        ),
    ]
