# Generated by Django 2.2.12 on 2020-05-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='end',
        ),
        migrations.RemoveField(
            model_name='member',
            name='start',
        ),
    ]
