# Generated by Django 2.2.12 on 2020-05-07 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_main_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='main_class',
        ),
    ]
