# Generated by Django 2.2.12 on 2020-05-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0012_delete_main_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ok', models.BooleanField()),
                ('members', models.ManyToManyField(to='myapi.Member')),
            ],
        ),
    ]
